# ==========================
# Stage 1: Build
# ==========================
FROM maven:3.9.9-eclipse-temurin-17 AS build

WORKDIR /app

# Copy project files
COPY pom.xml .
COPY src ./src

# Build Spring Boot application
RUN mvn clean package -DskipTests

# ==========================
# Stage 2: Runtime
# ==========================
FROM eclipse-temurin:17-jre

WORKDIR /app

# Copy generated jar
COPY --from=build /app/target/SBMVC-LibraryBookManagementSystem-0.0.1-SNAPSHOT.jar app.jar

# Spring Boot default port
EXPOSE 8080

# Run application
ENTRYPOINT ["java","-jar","app.jar"]